
courses:
  per_page: 15
subjects:
  per_page: 15
  name_min_len: 3
  des_min_len: 6
email_max_lengh: 255
password_min_lengh: 6
name_max_lengh: 50
address_max_lengh: 50
school_max_lengh: 50
gravatar_size: 50
check_remember: "1"
size_user: 50
